services:
  - type: web
    name: movie-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production 